[package]
name = "glfw-tutorials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
opengl = []

[dependencies]
gl = "0.14.0"
glfw = { version = "0.55.0", default-features = false }
